// SPDX-License-Identifier: Apache-2.0
//
// The agent-facing half of setoku.com (openapi.json, api/*.json) is a COMMITTED
// BUILD ARTIFACT generated by scripts/build-site-api.ts, the same way the admin
// bundles are. That means it can go stale: someone adds an MCP tool, ships it,
// and the published spec quietly describes the previous release.
//
// These tests pin the artifacts to the source they were derived from, so a
// forgotten `bun run build:site` fails the pre-push gate instead of shipping a
// spec that lies to whoever fetches it.
import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";

const ROOT = new URL("..", import.meta.url).pathname;
const readJson = (p: string) => Bun.file(ROOT + p).json();
const readText = (p: string) => Bun.file(ROOT + p).text();

/** Tool names, straight out of the gateway — the source of truth. */
async function sourceToolNames(): Promise<string[]> {
  const src = await readText("plugin/gateway/app.ts");
  return [...src.matchAll(/server\.registerTool\(\s*"([a-z_]+)"/g)].map((m) => m[1]);
}

describe("site API artifacts track the source", () => {
  test("tools.json lists exactly the tools the gateway registers", async () => {
    const published = await readJson("site/api/tools.json");
    const names = published.tools.map((t: { name: string }) => t.name);
    expect(names).toEqual(await sourceToolNames());
  });

  test("every published tool declares a real role", async () => {
    const published = await readJson("site/api/tools.json");
    const roles = Object.keys(published.roles);
    for (const t of published.tools) expect(roles).toContain(t.role);
  });

  test("the membrane is described accurately (I2)", async () => {
    // upsert_context / resolve_correction commit curated knowledge and are
    // registered only behind `if (canWrite)`. Publishing them as analyst-callable
    // would misdescribe the one security property people most need to trust.
    const published = await readJson("site/api/tools.json");
    const role = (n: string) =>
      published.tools.find((t: { name: string }) => t.name === n)?.role;
    expect(role("upsert_context")).toBe("curator");
    expect(role("resolve_correction")).toBe("curator");
    expect(role("report_correction")).toBe("analyst");
    expect(role("run_query")).toBe("analyst");
  });

  test("published version matches the plugin manifest", async () => {
    const { version } = await readJson("plugin/.claude-plugin/plugin.json");
    expect((await readJson("site/openapi.json")).info.version).toBe(version);
    expect((await readJson("site/api/index.json")).version).toBe(version);
    expect((await readJson("site/api/tools.json")).version).toBe(version);
  });

  test("openapi.json and api/openapi.json are the same document", async () => {
    expect(await readJson("site/api/openapi.json")).toEqual(
      await readJson("site/openapi.json"),
    );
  });
});

describe("the OpenAPI spec is well formed", () => {
  test("declares OpenAPI 3.1 and documents the MCP endpoint", async () => {
    const spec = await readJson("site/openapi.json");
    expect(spec.openapi).toStartWith("3.1");
    expect(Object.keys(spec.paths)).toContain("/mcp");
    expect(spec.paths["/mcp"].post.security).toEqual([{ bearerToken: [] }]);
  });

  test("credential-free endpoints are marked as such", async () => {
    // These are reachable without a token on a real box; an agent that thinks
    // they need auth will not call them.
    const spec = await readJson("site/openapi.json");
    for (const p of ["/healthz", "/p/{id}", "/p/{id}/data"]) {
      expect(spec.paths[p].get.security).toEqual([]);
    }
  });

  test("every $ref resolves", async () => {
    const spec = await readJson("site/openapi.json");
    const unresolved: string[] = [];
    const walk = (node: unknown, path: string): void => {
      if (!node || typeof node !== "object") return;
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        if (k === "$ref" && typeof v === "string") {
          let cur: unknown = spec;
          for (const seg of v.replace(/^#\//, "").split("/")) {
            cur = (cur as Record<string, unknown> | undefined)?.[seg];
          }
          if (cur === undefined) unresolved.push(`${path} -> ${v}`);
        } else walk(v, `${path}/${k}`);
      }
    };
    walk(spec, "");
    expect(unresolved).toEqual([]);
  });

  test("does not claim OAuth support we have not built", async () => {
    // docs/oauth-scoping.md records OAuth as scoped-but-deferred. Advertising it
    // here (or publishing authorization-server metadata) would send agents into
    // a flow with nothing behind it.
    const spec = await readJson("site/openapi.json");
    expect(Object.keys(spec.components.securitySchemes)).toEqual(["bearerToken"]);
    expect((await readJson("site/api/index.json")).mcp.auth.oauth2).toBe(false);
    expect(existsSync(ROOT + "site/.well-known/oauth-authorization-server")).toBe(false);
  });
});

describe("discovery files point at documents that exist", () => {
  /** https://setoku.com/x -> site/x, with /developers served as a directory. */
  const localPath = (url: string): string | null => {
    const m = url.match(/^https:\/\/setoku\.com(\/[^#?]*)/);
    if (!m) return null;
    const p = m[1];
    if (p === "/" || p.startsWith("/#")) return "site/index.html";
    return p.endsWith("/") ? `site${p}index.html` : `site${p}`;
  };

  test("llms.txt links resolve to real files", async () => {
    const txt = await readText("site/llms.txt");
    const missing: string[] = [];
    for (const [, url] of txt.matchAll(/\((https:\/\/setoku\.com[^)]*)\)/g)) {
      const p = localPath(url);
      if (!p) continue;
      // /developers is served by a rewrite to its index.html
      const candidates = [p, `${p}/index.html`];
      if (!candidates.some((c) => existsSync(ROOT + c))) missing.push(url);
    }
    expect(missing).toEqual([]);
  });

  test("sitemap lists only documents we ship", async () => {
    const xml = await readText("site/sitemap.xml");
    const missing: string[] = [];
    for (const [, loc] of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
      const p = localPath(loc);
      if (!p) continue;
      if (!existsSync(ROOT + p) && !existsSync(ROOT + `${p}/index.html`)) {
        missing.push(loc);
      }
    }
    expect(missing).toEqual([]);
  });

  test("robots.txt allows crawling and advertises the sitemap", async () => {
    const txt = await readText("site/robots.txt");
    expect(txt).toContain("Allow: /");
    expect(txt).toContain("Sitemap: https://setoku.com/sitemap.xml");
    expect(txt).not.toContain("Disallow: /\n");
  });

  test("both pages share one stylesheet, so they cannot drift apart", async () => {
    for (const p of ["site/index.html", "site/developers/index.html"]) {
      expect(await readText(p)).toContain('href="/assets/manpage.css"');
    }
    expect(existsSync(ROOT + "site/assets/manpage.css")).toBe(true);
  });

  test("the developer portal is reachable from the homepage", async () => {
    expect(await readText("site/index.html")).toContain('href="/developers"');
  });
});

describe("pages carry the structure crawlers and screen readers need", () => {
  const PAGES = ["site/index.html", "site/developers/index.html"];

  test("each page has exactly one h1", async () => {
    for (const p of PAGES) {
      const h1s = [...(await readText(p)).matchAll(/<h1[\s>]/g)];
      expect({ page: p, h1s: h1s.length }).toEqual({ page: p, h1s: 1 });
    }
  });

  test("the h1 names the product", async () => {
    for (const p of PAGES) {
      const h1 = (await readText(p)).match(/<h1[^>]*>([\s\S]*?)<\/h1>/)?.[1] ?? "";
      expect(h1.toLowerCase()).toContain("setoku");
    }
  });

  test("each page ships valid JSON-LD", async () => {
    for (const p of PAGES) {
      const blocks = [
        ...(await readText(p)).matchAll(
          /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,
        ),
      ];
      expect(blocks.length).toBe(1);
      const graph = JSON.parse(blocks[0][1])["@graph"];
      expect(Array.isArray(graph)).toBe(true);
      // Schema breadth: a lone SoftwareApplication answers far fewer questions
      // about the entity than a linked graph does.
      expect(graph.length).toBeGreaterThanOrEqual(3);
      for (const node of graph) {
        expect(node["@type"]).toBeString();
        expect(node["@id"]).toBeString();
      }
    }
  });

  test("JSON-LD @ids are shared across pages, not redeclared per page", async () => {
    // Both pages describe the same product and the same org. If the @ids drift,
    // a crawler sees two unrelated entities instead of one with two pages.
    const idsFor = async (p: string) => {
      const raw = (await readText(p)).match(
        /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
      )![1];
      return new Set<string>(
        JSON.parse(raw)["@graph"].map((n: { "@id": string }) => n["@id"]),
      );
    };
    const home = await idsFor("site/index.html");
    const devs = await idsFor("site/developers/index.html");
    for (const shared of ["https://setoku.com/#software", "https://setoku.com/#org"]) {
      expect(home.has(shared)).toBe(true);
      expect(devs.has(shared)).toBe(true);
    }
  });

  test("the organization declares sameAs links for entity resolution", async () => {
    const raw = (await readText("site/index.html")).match(
      /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
    )![1];
    const org = JSON.parse(raw)["@graph"].find(
      (n: { "@type": string }) => n["@type"] === "Organization",
    );
    expect(org.sameAs.length).toBeGreaterThan(0);
    expect(org.contactPoint.email).toBe("hello@setoku.com");
  });
});
