// SPDX-License-Identifier: Apache-2.0
//
// The agent-facing half of setoku.com (openapi.json, api/*.json) is a COMMITTED
// BUILD ARTIFACT generated by scripts/build-site-api.ts, the same way the admin
// bundles are. That means it can go stale: someone adds an MCP tool, ships it,
// and the published spec quietly describes the previous release.
//
// These tests pin the artifacts to the source they were derived from, so a
// forgotten `bun run build:site` fails the pre-push gate instead of shipping a
// spec that lies to whoever fetches it.
import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";

import { buildArtifacts, serialize } from "../scripts/build-site-api";

const ROOT = new URL("..", import.meta.url).pathname;
const readJson = (p: string) => Bun.file(ROOT + p).json();
const readText = (p: string) => Bun.file(ROOT + p).text();

describe("site API artifacts track the source", () => {
  // THE test. Everything else here is a readable assertion about a specific
  // property; this one is the actual guarantee, because it regenerates every
  // artifact from the source tree and diffs it against what is committed (and
  // therefore what gets published). An earlier version of this suite read the
  // committed files and spot-checked fields, which could not tell a correct
  // artifact from a stale one: only tool NAMES were compared to app.ts, so an
  // edited title, a moved capability block, or a new connector shipped stale
  // while the suite stayed green.
  test("committed artifacts are exactly what the generator produces now", async () => {
    const stale: string[] = [];
    for (const [p, body] of await buildArtifacts()) {
      const committed = await Bun.file(ROOT + p).text().catch(() => "");
      if (committed !== serialize(body)) stale.push(p);
    }
    expect({
      stale,
      hint: "run `bun run build:site` and commit the result",
    }).toEqual({ stale: [], hint: "run `bun run build:site` and commit the result" });
  });

  test("tools.json lists exactly the tools the gateway registers", async () => {
    // Independent of the generator's own regex: parse app.ts a different way so a
    // bug in the generator's extraction can't hide behind an identical bug here.
    const src = await readText("plugin/gateway/app.ts");
    const fromSource = src
      .split("\n")
      .map((l) => l.match(/^\s*"([a-z_0-9]+)",\s*$/))
      .filter((m, i, _a): m is RegExpMatchArray => {
        if (!m) return false;
        const lines = src.split("\n");
        return (lines[i - 1] ?? "").includes("server.registerTool(");
      })
      .map((m) => m[1]);
    const published = (await readJson("site/api/tools.json")).tools.map(
      (t: { name: string }) => t.name,
    );
    expect(published).toEqual(fromSource);
  });

  test("every published tool declares a real role", async () => {
    const published = await readJson("site/api/tools.json");
    const roles = Object.keys(published.roles);
    for (const t of published.tools) expect(roles).toContain(t.role);
  });

  test("the membrane is described accurately, checked against app.ts (I2)", async () => {
    // upsert_context / resolve_correction commit curated knowledge and are
    // registered only behind `if (canWrite)`. Publishing them as analyst-callable
    // would misdescribe the one security property people most need to trust — so
    // this reads the GATING OUT OF THE SOURCE, not out of the artifact it is
    // supposed to be validating.
    const src = await readText("plugin/gateway/app.ts");
    const within = (name: string, open: string, close: string): boolean => {
      const a = src.indexOf(open);
      const b = src.indexOf(close);
      const at = src.indexOf(`server.registerTool(\n  "${name}"`);
      expect({ marker: open, found: a >= 0 && b > a }).toEqual({ marker: open, found: true });
      expect({ tool: name, registered: at >= 0 }).toEqual({ tool: name, registered: true });
      return at > a && at < b;
    };
    expect(within("upsert_context", "if (canWrite) {", "} // end canWrite")).toBe(true);
    expect(within("resolve_correction", "if (canWrite) {", "} // end canWrite")).toBe(true);
    expect(within("draft_correction", "if (canDraft) {", "} // end canDraft")).toBe(true);
    expect(within("reject_correction", "if (canReject) {", "} // end canReject")).toBe(true);
    // …and that the published roles agree with that.
    const published = await readJson("site/api/tools.json");
    const role = (n: string) =>
      published.tools.find((t: { name: string }) => t.name === n)?.role;
    expect(role("upsert_context")).toBe("curator");
    expect(role("resolve_correction")).toBe("curator");
    expect(role("draft_correction")).toBe("janitor");
    expect(role("reject_correction")).toBe("janitor");
    expect(role("report_correction")).toBe("analyst");
    expect(role("run_query")).toBe("analyst");
  });

  test("published version matches the plugin manifest", async () => {
    const { version } = await readJson("plugin/.claude-plugin/plugin.json");
    expect((await readJson("site/openapi.json")).info.version).toBe(version);
    expect((await readJson("site/api/index.json")).version).toBe(version);
    expect((await readJson("site/api/tools.json")).version).toBe(version);
  });

  test("openapi.json and api/openapi.json are the same document", async () => {
    expect(await readJson("site/api/openapi.json")).toEqual(
      await readJson("site/openapi.json"),
    );
  });

  test("every ingest schema is represented in the connector catalog", async () => {
    // The generator throws on an unclaimed schema; assert that here too so the
    // failure surfaces in the test suite rather than only at deploy time.
    const glob = new Bun.Glob("*.sql");
    const schemas: string[] = [];
    for await (const f of glob.scan({ cwd: ROOT + "ingest/schemas" })) schemas.push(f);
    expect(schemas.length).toBeGreaterThan(0);
    const published = (await readJson("site/api/connectors.json")).connectors;
    expect(published.length).toBeGreaterThan(0);
    // buildArtifacts() would have thrown on an unclaimed schema, and the
    // regenerate-and-diff test above calls it, so reaching here means coverage
    // held. This asserts the catalog is non-trivially populated.
    for (const c of published) {
      expect(c.id).toBeString();
      expect(c.name).toBeString();
      expect(c.data).toBeString();
    }
  });
});

describe("the OpenAPI spec is well formed", () => {
  test("declares OpenAPI 3.1 and documents the MCP endpoint", async () => {
    const spec = await readJson("site/openapi.json");
    expect(spec.openapi).toStartWith("3.1");
    expect(Object.keys(spec.paths)).toContain("/mcp");
    expect(spec.paths["/mcp"].post.security).toEqual([{ bearerToken: [] }]);
  });

  test("credential-free endpoints are marked as such", async () => {
    // These are reachable without a token on a real box; an agent that thinks
    // they need auth will not call them.
    const spec = await readJson("site/openapi.json");
    for (const p of ["/healthz", "/p/{id}", "/p/{id}/data"]) {
      expect(spec.paths[p].get.security).toEqual([]);
    }
  });

  test("every $ref resolves", async () => {
    const spec = await readJson("site/openapi.json");
    const unresolved: string[] = [];
    const walk = (node: unknown, path: string): void => {
      if (!node || typeof node !== "object") return;
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        if (k === "$ref" && typeof v === "string") {
          let cur: unknown = spec;
          for (const seg of v.replace(/^#\//, "").split("/")) {
            cur = (cur as Record<string, unknown> | undefined)?.[seg];
          }
          if (cur === undefined) unresolved.push(`${path} -> ${v}`);
        } else walk(v, `${path}/${k}`);
      }
    };
    walk(spec, "");
    expect(unresolved).toEqual([]);
  });

  test("does not claim OAuth support we have not built", async () => {
    // docs/oauth-scoping.md records OAuth as scoped-but-deferred. Advertising it
    // here (or publishing authorization-server metadata) would send agents into
    // a flow with nothing behind it.
    const spec = await readJson("site/openapi.json");
    expect(Object.keys(spec.components.securitySchemes)).toEqual(["bearerToken"]);
    expect((await readJson("site/api/index.json")).mcp.auth.oauth2).toBe(false);
    expect(existsSync(ROOT + "site/.well-known/oauth-authorization-server")).toBe(false);
  });
});

describe("discovery files point at documents that exist", () => {
  /** https://setoku.com/x -> site/x, with /docs served as a directory. */
  const localPath = (url: string): string | null => {
    const m = url.match(/^https:\/\/setoku\.com(\/[^#?]*)/);
    if (!m) return null;
    const p = m[1];
    if (p === "/" || p.startsWith("/#")) return "site/index.html";
    return p.endsWith("/") ? `site${p}index.html` : `site${p}`;
  };

  test("llms.txt links resolve to real files", async () => {
    const txt = await readText("site/llms.txt");
    const missing: string[] = [];
    for (const [, url] of txt.matchAll(/\((https:\/\/setoku\.com[^)]*)\)/g)) {
      const p = localPath(url);
      if (!p) continue;
      // /docs is served by a rewrite to its index.html
      const candidates = [p, `${p}/index.html`];
      if (!candidates.some((c) => existsSync(ROOT + c))) missing.push(url);
    }
    expect(missing).toEqual([]);
  });

  test("sitemap lists only documents we ship", async () => {
    const xml = await readText("site/sitemap.xml");
    const missing: string[] = [];
    for (const [, loc] of xml.matchAll(/<loc>([^<]+)<\/loc>/g)) {
      const p = localPath(loc);
      if (!p) continue;
      if (!existsSync(ROOT + p) && !existsSync(ROOT + `${p}/index.html`)) {
        missing.push(loc);
      }
    }
    expect(missing).toEqual([]);
  });

  test("robots.txt allows crawling and advertises the sitemap", async () => {
    const txt = await readText("site/robots.txt");
    expect(txt).toContain("Allow: /");
    expect(txt).toContain("Sitemap: https://setoku.com/sitemap.xml");
    expect(txt).not.toContain("Disallow: /\n");
  });

  test("both pages share one stylesheet, so they cannot drift apart", async () => {
    for (const p of ["site/index.html", "site/docs/index.html"]) {
      expect(await readText(p)).toContain('href="/assets/manpage.css"');
    }
    expect(existsSync(ROOT + "site/assets/manpage.css")).toBe(true);
  });

  test("the API reference is reachable from the homepage", async () => {
    expect(await readText("site/index.html")).toContain('href="/docs"');
  });
});

describe("hand-written pages agree with the generated catalog", () => {
  /**
   * Tool names advertised in a page's `<span class="t">a · b</span>` subtitle
   * runs. `.t` is a general-purpose subtitle (the SECURITY section uses it for
   * "per-person · revocable"), so match only lower_snake_case identifiers —
   * every registered tool name contains an underscore, ordinary prose does not.
   */
  const TOOL_NAME = /^[a-z][a-z0-9]*(_[a-z0-9]+)+$/;

  async function proseToolNames(p: string): Promise<Set<string>> {
    const html = await readText(p);
    const names = new Set<string>();
    for (const [, run] of html.matchAll(/<span class="t">([^<]*)<\/span>/g)) {
      for (const part of run.split("·")) {
        const n = part.trim();
        if (TOOL_NAME.test(n)) names.add(n);
      }
    }
    return names;
  }

  test("/docs names only tools that actually exist", async () => {
    // The portal's tool list is prose — it can't import tools.json. So assert the
    // one direction that matters for a reader: every name it advertises is real.
    // It previously listed 17 of 19 and omitted the janitor role entirely, three
    // lines below a link to the JSON that said otherwise.
    const published = new Set<string>(
      (await readJson("site/api/tools.json")).tools.map((t: { name: string }) => t.name),
    );
    const bogus = [...(await proseToolNames("site/docs/index.html"))].filter(
      (n) => !published.has(n),
    );
    expect(bogus).toEqual([]);
  });

  test("/docs accounts for every tool and role", async () => {
    const catalog = await readJson("site/api/tools.json");
    const html = await readText("site/docs/index.html");
    const missing = catalog.tools
      .map((t: { name: string }) => t.name)
      .filter((n: string) => !html.includes(n));
    expect(missing).toEqual([]);
    // A role the page never mentions is a role a reader never learns about — and
    // the roles ARE the membrane.
    for (const role of Object.keys(catalog.roles)) {
      expect(html.toLowerCase()).toContain(role);
    }
  });

  test("the homepage names only tools that actually exist", async () => {
    const published = new Set<string>(
      (await readJson("site/api/tools.json")).tools.map((t: { name: string }) => t.name),
    );
    const bogus = [...(await proseToolNames("site/index.html"))].filter(
      (n) => !published.has(n),
    );
    expect(bogus).toEqual([]);
  });
});

describe("the agent-facing surface an agent probes for", () => {
  // Everything in this block is a document agents fetch by CONVENTION rather
  // than by following a link: the well-known paths, the markdown twins, and the
  // ?mode=agent view. Nothing on the site links to most of them, so a rename or
  // a Caddy edit can quietly unpublish one without a single broken link.
  const CADDY = "deploy/caddy.d/setoku-com.caddy";

  test("the well-known discovery files exist and are self-describing", async () => {
    const card = await readJson("site/.well-known/agent-card.json");
    expect(card.name).toBe("Setoku");
    expect(card.description).toContain("Setoku");
    expect(card.skills.length).toBeGreaterThan(2);
    for (const s of card.skills) {
      expect(s.name).toBeString();
      expect(s.description.length).toBeGreaterThan(20);
    }

    const skills = await readJson("site/.well-known/agent-skills/index.json");
    expect(skills.skills.length).toBeGreaterThan(2);
    for (const s of skills.skills) {
      expect(s.name).toBeString();
      expect(s.description.length).toBeGreaterThan(20);
    }

    const mcp = await readJson("site/.well-known/mcp.json");
    expect(mcp.remotes.some((r: { type: string }) => r.type === "streamable-http")).toBe(true);
    expect(mcp.auth.oauth2).toBe(false);
  });

  test("the skill index publishes exactly the skills we ship", async () => {
    const glob = new Bun.Glob("*/SKILL.md");
    const dirs: string[] = [];
    for await (const f of glob.scan({ cwd: ROOT + "plugin/skills" })) dirs.push(f.split("/")[0]);
    const published = (await readJson("site/.well-known/agent-skills/index.json")).skills.map(
      (s: { name: string }) => s.name,
    );
    expect(published.sort()).toEqual(dirs.sort());
  });

  test("every discovery file says WHEN to use Setoku, not just what it is", async () => {
    // The one thing marketing copy never states outright, and the thing an agent
    // most needs in order to decide whether to reach for us at all.
    for (const p of [
      "site/.well-known/agent-card.json",
      "site/.well-known/mcp.json",
      "site/.well-known/agent-skills/index.json",
    ]) {
      const doc = await readJson(p);
      const when = doc.whenToUse ?? doc.when_to_use;
      expect({ file: p, hasGuidance: !!when }).toEqual({ file: p, hasGuidance: true });
      expect(when.use_when.length).toBeGreaterThan(2);
      expect(when.do_not_use_when.length).toBeGreaterThan(2);
      expect(when.how_to_call.join(" ")).toContain("find_context");
    }
    // The prose pages state the same rule in the same words, so an agent that
    // reads llms.txt and an agent that reads the markdown twin get one answer.
    for (const p of ["site/llms.txt", "site/index.md", "site/docs.md"]) {
      expect(await readText(p)).toContain("Reach for Setoku when the answer lives in");
    }
  });

  test("the markdown twins are markdown, and lead with a heading", async () => {
    for (const p of ["site/index.md", "site/docs.md"]) {
      const body = await readText(p);
      expect({ page: p, first: body.split("\n")[0] }).toEqual({
        page: p,
        first: p.endsWith("index.md") ? "# Setoku" : "# Setoku API reference",
      });
      expect(body).not.toContain("<html");
      // Straight apostrophes are a site-copy smell (CLAUDE.md), and these pages
      // are generated, so a regression here is a generator bug, not a typo.
      expect(body).not.toMatch(/[A-Za-z]'[A-Za-z]/);
    }
  });

  test("angle-bracket placeholders survive being rendered", async () => {
    // `<their-box>` outside a code span is a raw-HTML tag in CommonMark, and
    // every renderer swallows it: `https://<their-box>/mcp/<token>` displayed as
    // `https:///mcp/`, silently deleting the host and the token out of the one
    // instruction these pages most need to get right. Either escape it or put it
    // in backticks — this checks the rendered result rather than the technique.
    for (const p of ["site/index.md", "site/docs.md", "site/llms.txt"]) {
      const swallowed: string[] = [];
      // strip fenced/indented code and code spans: inside them `<` is literal
      const text = (await readText(p))
        .split("\n")
        .filter((l) => !l.startsWith("    "))
        .join("\n")
        .replace(/`[^`]*`/g, "");
      // `\<` is a CommonMark backslash escape and renders as a literal `<`.
      for (const [, m] of text.matchAll(/(?:^|[^\\])(<[A-Za-z][A-Za-z0-9-]*>)/g)) {
        swallowed.push(m);
      }
      expect({ page: p, swallowed }).toEqual({ page: p, swallowed: [] });
    }
  });

  test("the box's error shape is documented as the spec declares it", async () => {
    // /docs.md used to promise a structured {code, message, hint} envelope
    // from every endpoint. The gateway returns {ok:false, error:"<string>"} —
    // which is what the openapi.json emitted by this same generator says — so
    // the published docs contradicted the published spec in one build, and an
    // integrator branching on `error.code` matched nothing forever.
    const spec = await readJson("site/openapi.json");
    expect(spec.components.schemas.Error.properties.error.type).toBe("string");
    const md = await readText("site/docs.md");
    expect(md).toContain('{ "ok": false, "error": "app not found or archived" }');
  });

  test("/docs.md describes the membrane the way app.ts implements it", async () => {
    // Only the curator/janitor tools are registration-gated; the analyst surface
    // is registered on EVERY session and the lake block is a call-time refusal.
    // Publishing "the tools of the others are never registered" made a false
    // statement about I2 on a public URL — the exact thing tools() throws to
    // prevent — and told a curator session that find_context was unavailable.
    const md = await readText("site/docs.md");
    expect(md).toContain("registered on every session");
    expect(md).toContain("refuses lake queries");
    expect(md).not.toContain("The tools of the others are not merely refused");
  });

  test("both HTML pages advertise their markdown twin", async () => {
    for (const [html, md] of [
      ["site/index.html", "https://setoku.com/index.md"],
      ["site/docs/index.html", "https://setoku.com/docs.md"],
    ]) {
      const head = await readText(html);
      expect(head).toContain('type="text/markdown"');
      expect(head).toContain(md);
    }
  });

  test("Caddy actually serves that surface (the files alone are not enough)", async () => {
    // These behaviours were verified against caddy:2 locally; this pins the
    // directives so an edit to the vhost cannot silently drop one. Without the
    // Content-Type line, .md files go out as text/plain and a client checking
    // the header concludes we do not serve markdown at all.
    const conf = await readText(CADDY);
    expect(conf).toContain('header @md Content-Type "text/markdown; charset=utf-8"');
    expect(conf).toContain('{query.mode} == "agent"');
    expect(conf).toContain("rewrite * /index.md");
    expect(conf).toContain("rewrite * /docs.md");
    expect(conf).toContain("handle_errors");
    expect(conf).toContain('"code":"not_found"');
    // Unmatched, so a newly published document is covered the day it lands. The
    // per-path list this replaced had already missed /sitemap.xml — the file
    // that enumerates the discovery documents for a browser-based agent.
    expect(conf).toMatch(/^\theader Access-Control-Allow-Origin \*$/m);
    // The HTML branch of the 404 has to have something to serve.
    expect(conf).toContain("rewrite * /404.html");
    expect(existsSync(ROOT + "site/404.html")).toBe(true);
  });

  test("api/index.json really does list everything the site publishes", async () => {
    // Both 404 surfaces (the JSON body in the vhost and site/404.html) send
    // readers to this file as the complete index, so "complete" has to be true:
    // the five discovery documents were added to the build without reaching it,
    // and an agent following that hint concluded we ship no MCP manifest at all.
    const published: string[] = (await readJson("site/api/index.json")).publishes;
    const artifacts = (await buildArtifacts()).map(
      ([p]) => `https://setoku.com${p.slice("site".length)}`,
    );
    const missing = artifacts.filter((u) => !published.includes(u));
    expect({ missing, hint: "add it to `publishes` in scripts/build-site-api.ts" }).toEqual({
      missing: [],
      hint: "add it to `publishes` in scripts/build-site-api.ts",
    });
    // …and the other direction: nothing listed that we do not actually serve.
    const phantom = published.filter((u) => {
      const p = u.replace("https://setoku.com", "site");
      return !existsSync(ROOT + (p === "site/" ? "site/index.html" : p)) &&
        !existsSync(ROOT + `${p}/index.html`);
    });
    expect(phantom).toEqual([]);
  });

  test("the JSON error body in the Caddy config is valid JSON with a code and a hint", async () => {
    const conf = await readText(CADDY);
    const bodies = [...conf.matchAll(/respond `([\s\S]*?)`\s/g)].map((m) => m[1]);
    expect(bodies.length).toBeGreaterThan(1);
    for (const raw of bodies) {
      // {err.status_code} is a Caddy placeholder; substitute a number so the
      // rest can be parsed. A body that only *looks* like JSON is the exact
      // failure this catches — agents cannot parse an HTML error page, and they
      // cannot parse a malformed one either.
      const doc = JSON.parse(raw.replace(/\{err\.status_code\}/g, "500"));
      expect(doc.ok).toBe(false);
      expect(doc.error.code).toBeString();
      expect(doc.error.message).toBeString();
      expect(doc.error.hint.length).toBeGreaterThan(20);
      expect(doc.error.docs).toStartWith("https://setoku.com");
    }
  });
});

describe("pages carry the structure crawlers and screen readers need", () => {
  const PAGES = ["site/index.html", "site/docs/index.html"];

  test("each page has exactly one h1", async () => {
    for (const p of PAGES) {
      const h1s = [...(await readText(p)).matchAll(/<h1[\s>]/g)];
      expect({ page: p, h1s: h1s.length }).toEqual({ page: p, h1s: 1 });
    }
  });

  test("the h1 names the product", async () => {
    for (const p of PAGES) {
      const h1 = (await readText(p)).match(/<h1[^>]*>([\s\S]*?)<\/h1>/)?.[1] ?? "";
      expect(h1.toLowerCase()).toContain("setoku");
    }
  });

  test("each page ships valid JSON-LD", async () => {
    for (const p of PAGES) {
      const blocks = [
        ...(await readText(p)).matchAll(
          /<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,
        ),
      ];
      expect(blocks.length).toBe(1);
      const graph = JSON.parse(blocks[0][1])["@graph"];
      expect(Array.isArray(graph)).toBe(true);
      // Schema breadth: a lone SoftwareApplication answers far fewer questions
      // about the entity than a linked graph does.
      expect(graph.length).toBeGreaterThanOrEqual(3);
      for (const node of graph) {
        expect(node["@type"]).toBeString();
        expect(node["@id"]).toBeString();
      }
    }
  });

  test("JSON-LD @ids are shared across pages, not redeclared per page", async () => {
    // Both pages describe the same product and the same org. If the @ids drift,
    // a crawler sees two unrelated entities instead of one with two pages.
    const idsFor = async (p: string) => {
      const raw = (await readText(p)).match(
        /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
      )![1];
      return new Set<string>(
        JSON.parse(raw)["@graph"].map((n: { "@id": string }) => n["@id"]),
      );
    };
    const home = await idsFor("site/index.html");
    const devs = await idsFor("site/docs/index.html");
    for (const shared of ["https://setoku.com/#software", "https://setoku.com/#org"]) {
      expect(home.has(shared)).toBe(true);
      expect(devs.has(shared)).toBe(true);
    }
  });

  test("the organization declares sameAs links for entity resolution", async () => {
    const raw = (await readText("site/index.html")).match(
      /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
    )![1];
    const org = JSON.parse(raw)["@graph"].find(
      (n: { "@type": string }) => n["@type"] === "Organization",
    );
    expect(org.sameAs.length).toBeGreaterThan(0);
    expect(org.contactPoint.email).toBe("hello@setoku.com");
  });
});
